// export const ADD_EVENT = 'ADD_EVENT';
// export const CHANGE_SELECTED_EVENT = 'CHANGE_SELECTED_EVENT';
// export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST';
// export const ADD_EVENTS = 'ADD_EVENTS';
// export const ADD_SELECTED_EVENT = 'ADD_SELECTED_EVENT';
// export const DELETE_EVENT = 'DELETE_EVENT';

export const ADD_EVENT = 'ADD_EVENT';
export const CHANGE_SELECTED_EVENT = 'CHANGE_SELECTED_EVENT';
export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST';
export const ADD_EVENTS = 'ADD_EVENTS';
export const ADD_SELECTED_EVENT = 'ADD_SELECTED_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
